### PR TITLE
Feature to enable / disable firewall logging for dropped packets...

### PR DESCRIPTION
**Pull request by snkutlu**

### CODE REVIEW

**Comment by svanharmelen** [comment]
@snkutlu I don't think this is the right approach. I think you should implement some logic so the windows provider knows what to do with getting a rule with the logging attribute set: https://github.com/schubergphilis/firewall/blob/master/libraries/resource_firewall_rule.rb#L23

**Comment by snkutlu** [comment]
@svanharmelen the one you mentioned is per rule logging. But what we want to achive is to log all dropped packets in active profile so that we can trace back an issue if it is related with host based firewall. 

We should not put this into rule provider for another reason as well: This code piece should be executed each time firewall cookbook default recipe is called regardless of rule set is changes. There may be no change in ruleset but we may want to enable / disable logging of dropped packets. 

This is why I tried to implement like that..

**Comment by shoekstra** [comment]
> This code piece should be executed each time firewall cookbook default recipe is called regardless of rule set is changes.

Agree with @svanharmelen - the above statement should really be avoided as recipes should be idempotent.  You want to get a point where changes in Chef runs are noticeable so you are aware if the managed system is drifting from it's desired configuration.

**Comment by shoekstra** [comment]
Also may want to add some basic tests and describe the attribute in the README so people know about it?

**Comment by snkutlu** [comment]
@shoekstra This feature to set logging is independent from rules, so how do you suggest to enable / disable this via firewall recipe? 

Desired configuration set by attribute is either enable or disable dropped packet logging. This may happen on a running system to enable for a while to see logging for debugging purposes. If we keep this in firewall_rule provider, it will not be handled if no rules changed. Either I will create a new provider just to enable / disable logging or (as I did here) as default recipe is always run in each chef run and is trying to install service, it will also check existing situation of "logging of dropped packets" and desired state and act accordingly. 

I am open to suggestions on how to proceed :)

**Comment by snkutlu** [comment]
And yes for documentation and testing, I agree.. Although testing needs more time for me, documentation is easy.

**Comment by snkutlu** [comment]
Will be handled differently...

**Pull request closed without merging**
